# Assumes that you are running from this directory.
#
# ansible-playbook -i "localhost," -c local -K config.yml
#
---
- hosts: all
  roles:
      - { role: neovim }
      - { role: hub }
      - { role: bash }
      - { role: rust }
      - { role: dot_files}

  tasks:
    - name: Disable apport (Ubuntu bug notification service)
      lineinfile:
        dest: /etc/default/apport
        regexp: '^enabled='
        line: 'enabled=0'
      become: yes
